### ISSUE TITLE
Dialog: Error!!! std::bad_alloc in Village Ruins

### ISSUE THREAD

**Issue by clort81** [calref/cboe#209]
![dialog-villageruins](https://user-images.githubusercontent.com/51511737/71760039-75e42400-2eb7-11ea-995d-c6a16f626287.png)
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Thread 1 "Blades of Exile" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x0000007fb779ae68 in __GI_abort () at abort.c:79
#2  0x0000007fb7a51278 in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#3  0x0000007fb7a4efac in ?? () from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#4  0x0000007fb7a4f000 in std::terminate() () from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#5  0x0000007fb7a4f330 in __cxa_rethrow () from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#6  0x000000555562e634 in main (argc=1, argv=0x7fffffeda8) at build/obj/game/boe.main.cpp:128
```

**Comment by CelticMinstrel** [comment]
Is this reproduceable? If it can be reliably reproduced, it might be nice to get a stack trace of the actual original throw point (rather than the rethrow in main). The way to do that (if it is indeed reliably reproduceable) would be to comment out the exception handler in main.

**Comment by clort81** [comment]
Got another one talking to the guy in the foundry. 
![badalloc2](https://user-images.githubusercontent.com/51511737/71762576-172ba400-2ed1-11ea-8774-e388e9111627.png)

**Comment by clort81** [comment]
Disabled the exception handler in main and got a backtrace:
```
[New Thread 0x7fb50dd090 (LWP 19200)]
[New Thread 0x7fb46b5090 (LWP 19201)]
[New Thread 0x7faffff090 (LWP 19202)]
[Thread 0x7faffff090 (LWP 19202) exited]
_NET_WM_STATE_ABOVE has atom of 325
_NET_WM_STATE has atom of 324
[Detaching after vfork from child process 19204]
Warning: Missing opcode definition for special node type with ID 56
Warning: Missing opcode definition for special node type with ID 57
Warning: Missing opcode definition for special node type with ID 59
Warning: Missing opcode definition for special node type with ID 60

Thread 1 "Blades of Exile" received signal SIGSEGV, Segmentation fault.
__memcpy_generic () at ../sysdeps/aarch64/multiarch/../memcpy.S:99
99	../sysdeps/aarch64/multiarch/../memcpy.S: No such file or directory.
(gdb) bt
#0  __memcpy_generic () at ../sysdeps/aarch64/multiarch/../memcpy.S:99
#1  0x0000007fb7ae0820 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#2  0x0000007fb7ae0b64 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#3  0x0000005555687fac in get_strs (
    str1="There's nothing left here now, except for a grim warning of what the Vale will look like if the curse is left unchecked.", str2="", cur_type=1, which_str1=26, which_str2=27) at build/obj/game/boe.specials.cpp:4626
#4  0x000000555567ae1c in oneshot_spec (which_mode=eSpecCtx::OUT_MOVE, cur_node=..., cur_spec_type=1, 
    next_spec=0x7fffffa89e, next_spec_type=0x7fffffa89c, a=0x7fffffaa36, b=0x7fffffaa34, redraw=0x7fffffaa32)
    at build/obj/game/boe.specials.cpp:2551
#5  0x0000005555677f14 in run_special (which_mode=eSpecCtx::OUT_MOVE, which_type=1, start_spec=21, spec_loc=..., 
    a=0x7fffffaa36, b=0x7fffffaa34, redraw=0x7fffffaa32) at build/obj/game/boe.specials.cpp:2040
#6  0x000000555566b0e4 in check_special_terrain (where_check=..., mode=eSpecCtx::OUT_MOVE, which_pc=..., 
    forced=0x7fffffb1f7) at build/obj/game/boe.specials.cpp:170
#7  0x0000005555591f10 in outd_move_party (destination=..., forced=false) at build/obj/game/boe.actions.cpp:2812
#8  0x0000005555583aec in handle_move (destination=..., did_something=@0x7fffffbb28: false, 
    need_redraw=@0x7fffffbb29: false, need_reprint=@0x7fffffbb27: false) at build/obj/game/boe.actions.cpp:482
#9  0x00000055555878a0 in handle_action (event=...) at build/obj/game/boe.actions.cpp:1144
#10 0x000000555558a3cc in handle_keystroke (event=...) at build/obj/game/boe.actions.cpp:1682
#11 0x0000005555630bd4 in Handle_One_Event () at build/obj/game/boe.main.cpp:236
#12 0x00000055556301e8 in main (argc=1, argv=0x7fffffeda8) at build/obj/game/boe.main.cpp:122
(gdb) 
```

**Comment by x-qq** [comment]
I have loaded your savegame and moved the party south into the special node, but I did not get a crash.

Cannot reproduce.
