### ISSUE TITLE
Segmentation Fault when starting OBoE on Linux

### ISSUE THREAD

**Issue by seisatsu** [calref/cboe#272]
Running on Void Linux, I get an immediate segmentation fault when trying to run Blades of Exile after compiling with scons. What additional information would be helpful here?

**GDB Output**
```
#0  ProcExtsFromExtString (strExtList=0x0) at /builddir/SFML-2.5.1/src/SFML/Window/Unix/GlxExtensions.cpp:203
#1  sfglx_LoadFunctions (display=<optimized out>, screen=<optimized out>) at /builddir/SFML-2.5.1/src/SFML/Window/Unix/GlxExtensions.cpp:216
#2  0x00007ffff7d67c35 in sf::priv::ensureExtensionsInit (screen=<optimized out>, display=<optimized out>)
    at /builddir/SFML-2.5.1/src/SFML/Window/Unix/GlxContext.cpp:92
#3  sf::priv::GlxContext::GlxContext (this=0x555555a26790, shared=0x0) at /builddir/SFML-2.5.1/src/SFML/Window/Unix/GlxContext.cpp:112
#4  0x00007ffff7d5976f in sf::priv::GlContext::initResource () at /builddir/SFML-2.5.1/src/SFML/Window/GlContext.cpp:259
#5  0x00007ffff7d1213e in sf::Texture::Texture (this=0x5555559e6228 <talk_gworld+488>) at /builddir/SFML-2.5.1/src/SFML/Graphics/Texture.cpp:62
#6  0x00007ffff7d0bf83 in sf::RenderTexture::RenderTexture (this=0x5555559e6040 <talk_gworld>) at /builddir/SFML-2.5.1/src/SFML/Graphics/RenderTexture.cpp:37
#7  0x00005555555db471 in __static_initialization_and_destruction_0(int, int) ()
#8  0x00005555555db6bf in _GLOBAL__sub_I_sign_mode ()
#9  0x00005555558ab775 in __libc_csu_init ()
#10 0x00007ffff719cd7a in __libc_start_main (main=0x555555639542 <main>, argc=1, argv=0x7fffffffe598, init=0x5555558ab730 <__libc_csu_init>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffe588) at ../csu/libc-start.c:264
#11 0x000055555557af1a in _start () at ../sysdeps/x86_64/start.S:120
```

**Comment by x-qq** [comment]
This looks like you don't have opengl/glx loaded. Are you running under xorg? If so you can check using glxinfo too.

**Comment by seisatsu** [comment]
You are right, it's a fresh install, so I probably am missing some GL packages.
